CREATE TABLE APJ_ACTOR_PRINCIPAL(
ID_ACT_PRINCIPAL VARCHAR(10),
NOM_ACT_PRINCIPAL VARCHAR(20),
TEL_ACT_PRINCIPAL VARCHAR(20),
DOMICILIO VARCHAR(20)
);
CREATE TABLE APJ_PAPEL(
CVE_PAPEL VARCHAR(10),
DESCRIPCION VARCHAR (20),
PAGO VARCHAR(20),
EDAD VARCHAR(20)
);
CREATE TABLE APJ_PELICULA(
CVE_PEL VARCHAR (10),
DESCRIPCION VARCHAR(50),
TIPO_PEL VARCHAR (20),
DURACION VARCHAR(20)
);
CREATE TABLE APJ_EXTRA(
DNI_EXTRA VARCHAR(10),
EXTRA VARCHAR(20),
TEL_EXTRA VARCHAR(20),
EXTRA_DIRECCION VARCHAR(20)
);
CREATE TABLE APJ_ACTOR_PELICULA(
DNI_ACTOR VARCHAR(20),
CLAVE_PELICULA VARCHAR(20)
);

INSERT INTO APJ_ACTOR_PRINCIPAL(ID_ACT_PRINCIPAL, NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DOMICILIO)
VALUES ('A1','Juana Perez','56-57-20','Av 13');
INSERT INTO APJ_ACTOR_PRINCIPAL(ID_ACT_PRINCIPAL, NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DOMICILIO)
VALUES ('A2','Luis Gomez','14-34-12','Calle Zapotecas');
INSERT INTO APJ_ACTOR_PRINCIPAL(ID_ACT_PRINCIPAL, NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DOMICILIO)
VALUES ('A3','Maria Guzman','78-40-13','Periferico 123');
INSERT INTO APJ_ACTOR_PRINCIPAL(ID_ACT_PRINCIPAL, NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DOMICILIO)
VALUES ('A4','Pedro Juarez','77-34-90','Oriente 45');

INSERT INTO APJ_PAPEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P1','Protagonista','10000','20');
INSERT INTO APJ_PAPEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P2','Secundario','8000','21');
INSERT INTO APJ_PAPEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P3','De reparto','5000','19');
INSERT INTO APJ_PAPEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P4','De pequenas partes','2500','22');
INSERT INTO APJ_PAPEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P5','Figurante','2000','23');

INSERT INTO APJ_PELICULA(CVE_PEL, DESCRIPCION,TIPO_PEL,DURACION)
VALUES('PEL1','El fin del mundo','ACCION','3');
INSERT INTO APJ_PELICULA(CVE_PEL, DESCRIPCION,TIPO_PEL,DURACION)
VALUES('PEL2','El regreso de Chuky','TERROR','2');
INSERT INTO APJ_PELICULA(CVE_PEL, DESCRIPCION,TIPO_PEL,DURACION)
VALUES('PEL3','El pais de las maravillas','FANTASIA','2.5');
INSERT INTO APJ_PELICULA(CVE_PEL, DESCRIPCION,TIPO_PEL,DURACION)
VALUES('PEL4','Mi suegra','COMEDIA','2');

INSERT INTO APJ_EXTRA(DNI_EXTRA,EXTRA, TEL_EXTRA, EXTRA_DIRECCION)
VALUES ('A5','Ana Juarez','56-57-20','Av 20');
INSERT INTO APJ_EXTRA(DNI_EXTRA,EXTRA, TEL_EXTRA, EXTRA_DIRECCION)
VALUES ('A2','Luis Gomez','14-34-12','Calle Zapotecas');
INSERT INTO APJ_EXTRA(DNI_EXTRA,EXTRA, TEL_EXTRA, EXTRA_DIRECCION)
VALUES ('A6','Daniel Lopez','78-40-13','Sur 18');
INSERT INTO APJ_EXTRA(DNI_EXTRA,EXTRA, TEL_EXTRA, EXTRA_DIRECCION)
VALUES ('A4','Pedro Juarez','77-34-90','Oriente 45');

INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A1','PEL1');
INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A2','PEL1');
INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A3','PEL1');
INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A4','PEL2');
INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A5','PEL3');
INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A6','PEL4');
INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A1','PEL2');
INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A5','PEL1');
INSERT INTO APJ_ACTOR_PELICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A6','PEL3');

SELECT * FROM APJ_ACTOR_PELICULA;
SELECT * FROM APJ_ACTOR_PRINCIPAL;
SELECT * FROM APJ_EXTRA;
SELECT * FROM APJ_PAPEL;

SELECT NOM_ACT_PRINCIPAL,TEL_ACT_PRINCIPAL
FROM APJ_ACTOR_PRINCIPAL
UNION
SELECT EXTRA, TEL_EXTRA
FROM APJ_EXTRA

SELECT NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DESCRIPCION PELICULA
FROM APJ_ACTOR_PRINCIPAL, APJ_PELICULA, APJ_ACTOR_PELICULA
WHERE ID_ACT_PRINCIPAL = DNI_ACTOR AND CVE_PEL= CLAVE_PELICULA
UNION 
SELECT EXTRA, TEL_EXTRA, DESCRIPCION
FROM APJ_EXTRA, APJ_PELICULA, APJ_ACTOR_PELICULA
WHERE DNI_EXTRA=DNI_ACTOR AND CLAVE_PELICULA=CVE_PEL;

CREATE VIEW APJ_TODOS_ACTORES AS(
SELECT *
FROM APJ_ACTOR_PRINCIPAL
UNION 
SELECT *
FROM APJ_EXTRA);

SELECT * FROM APJ_TODOS_ACTORES;

SELECT NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL
FROM APJ_ACTOR_PRINCIPAL
INTERSECT
SELECT  EXTRA, TEL_EXTRA
FROM APJ_EXTRA;

SELECT NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL
FROM APJ_ACTOR_PRINCIPAL
INTERSECT
SELECT EXTRA, TEL_EXTRA
FROM APJ_EXTRA;

CREATE VIEW APJ_LAS_TABLAS AS(
SELECT * FROM APJ_TODOS_ACTORES INNER JOIN APJ_ACTOR_PELICULA
ON  ID_ACT_PRINCIPAL= DNI_ACTOR INNER JOIN APJ_PELICULA
ON CLAVE_PELICULA = CVE_PEL);

SELECT * FROM APJ_LAS_TABLAS;


SELECT DESCRIPCION, DESCRIPCION
FROM APJ_PAPEL, APJ_PELICULA;

SELECT NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DESCRIPCION, ACTORES_PELICULA
WHERE APJ_ACT_PRINCIPAL=DNI_ACTOR AND CLAVE_PEL=CVE_PEL

SELECT NOM_ACT_PRINCIPAL, TEL, DESCRFROM ACTORES PELICULA ACTOR PELICULA
WHERE IF APJ_ACT_PRINCIPAL DNI ACTOR 1 AND CLAVE PEL1=CVE_PEL

select nom_extra,  extra_direccionfrom apj_extra
except select nom_principal, domicio-act
from APJ_ACTOR_PRINCIPAL

SELECT EXTRA, EXTRA_DIRECCION, APJ_EXTRA
EXCEPT SELECT nom_principal, domicio-act
FROM APJ_ACTOR_PRINCIPAL