USE APJBSDA;

/*TABLAS*/
CREATE TABLE APJ_SEDE(
CVE_SEDE INT PRIMARY KEY NOT NULL,
NOMBRE_SEDE VARCHAR (15),
CIUDAD_SEDE VARCHAR (15),
UBICACION_SEDE VARCHAR (40),
NOMBRE_DIRECTOR_SEDE VARCHAR(20)
);

CREATE TABLE APJ_SOCIO(
ID_SOCIO INT PRIMARY KEY NOT NULL,
NOMBRE_SOCIO VARCHAR (20),
DIRECCION_SOCIO VARCHAR (40),
TELEFONO_SOCIO VARCHAR (10),
CUENTA_SOCIO VARCHAR (18),
TIPO_CUOTA VARCHAR(1),
IMPORTE INT,
FECHA_PAGO VARCHAR (10),
CVE_SEDE1 INT FOREIGN KEY REFERENCES APJ_SEDE (CVE_SEDE)
);

CREATE TABLE APJ_VOL_ADMINISTRATIVO(
ID_ADMIN INT PRIMARY KEY NOT NULL,
NSS_ADMIN VARCHAR (11),
EDAD_ADMIN INT,
NOMBRE_ADMIN VARCHAR (20),
TEL_ADMIN VARCHAR (10),
DIRECCION_ADMIN VARCHAR (40),
CVE_SEDE2 INT FOREIGN KEY REFERENCES APJ_SEDE(CVE_SEDE)
);

CREATE TABLE APJ_VOL_SANITARIO(
ID_SANIT INT PRIMARY KEY NOT NULL,
NSS_SANIT VARCHAR (11),
EDAD_SANIT INT,
DIRECCION_SANIT VARCHAR (40),
PROFESION_SANIT VARCHAR (30),
DISPONIBILIDAD_SANIT VARCHAR (2),
NUM_TRABAJOS_SANIT INT, 
TEL_SANIT VARCHAR (10),
CVE_SEDE3 INT FOREIGN KEY REFERENCES APJ_SEDE (CVE_SEDE)
);

CREATE TABLE APJ_ENVIO_ALIMENTO(
CVE_ENVIOA INT PRIMARY KEY NOT NULL,
DESTINO_ENVIOA VARCHAR (20),
FECHA_SALIDA_ENVIOA VARCHAR (10),
SEDE_ENVIOA VARCHAR (15)
);

CREATE TABLE APJ_ALIMENTO(
CVE_ALIMENTO INT PRIMARY KEY NOT NULL,
TIPO_ALIMENTO VARCHAR (20),
DESCRIPCION_ALIMENTO VARCHAR (20)
);

CREATE TABLE APJ_ENVIO_ALIMENTICIO_ALIMETOS(
CVE_ENVIOA1 INT FOREIGN KEY REFERENCES APJ_ENVIO_ALIMENTO (CVE_ENVIOA),
CVE_ALIMENTO1 INT FOREIGN KEY REFERENCES APJ_ALIMENTO(CVE_ALIMENTO),
NUMERO_TONELADAS INT
);

CREATE TABLE APJ_ENVIO_MEDICAMENTO11(
CVE_ENVIOM INT PRIMARY KEY NOT NULL,
DESTINO_ENVIOM VARCHAR (20),
FECHA_SALIDA_ENVIOM VARCHAR (10),
SEDE_ENVIOM INT FOREIGN KEY REFERENCES APJ_SEDE(CVE_SEDE)
);
INSERT APJ_ENVIO_MEDICAMENTO11(CVE_ENVIOM,DESTINO_ENVIOM,FECHA_SALIDA_ENVIOM,SEDE_ENVIOM)
VALUES (01, 'Ucrania', '29/05/2024',1);
INSERT APJ_ENVIO_MEDICAMENTO(CVE_ENVIOM,DESTINO_ENVIOM,FECHA_SALIDA_ENVIOM,SEDE_ENVIOM)
VALUES (02, 'Ucrania', '29/05/2024',2);
INSERT APJ_ENVIO_MEDICAMENTO(CVE_ENVIOM,DESTINO_ENVIOM,FECHA_SALIDA_ENVIOM,SEDE_ENVIOM)
VALUES (03, 'Palestina', '29/05/2024',3);

SELECT * FROM APJ_ENVIO_MEDICAMENTO;
SELECT * FROM APJ_SEDE;

UPDATE APJ_ENVIO_MEDICAMENTO SET SEDE_ENVIOM=1 WHERE SEDE_ENVIOM='Sandy ORG';
UPDATE APJ_ENVIO_MEDICAMENTO SET SEDE_ENVIOM=2 WHERE SEDE_ENVIOM='Parade COOP';

CREATE TABLE APJ_MEDICAMENTO(
CVE_MEDICAMENTO INT PRIMARY KEY NOT NULL,
TIPO_MEDICAMENTO VARCHAR (20),
DESCRIPCION_MEDICAMENTO VARCHAR (20)
);

CREATE TABLE APJ_ENVIO_MEDICAMENTO_MEDICINAS(
CVE_ENVIOM1 INT FOREIGN KEY REFERENCES APJ_ENVIO_MEDICAMENTO (CVE_ENVIOM),
CVE_MEDICAMENTO1 INT FOREIGN KEY REFERENCES APJ_MEDICAMENTO (CVE_MEDICAMENTO),
NUMERO_UNIDADES INT
);

CREATE TABLE APJ_ENVIO_PERSONAL(
CVE_ENVIOP INT PRIMARY KEY NOT NULL,
DESTINO_ENVIOP VARCHAR (20),
FECHA_SALIDA_ENVIOP VARCHAR (10)
);

CREATE TABLE APJ_ENVIO_PERSONAL_SANITARIO(
CVE_ENVIOP1 INT FOREIGN KEY REFERENCES APJ_ENVIO_PERSONAL (CVE_ENVIOP),
ID_SANIT1 INT FOREIGN KEY REFERENCES APJ_VOL_SANITARIO (ID_SANIT),
NUMERO_TONELADAS INT
);
SELECT * FROM APJ_SEDE;
SELECT * FROM APJ_VOL_ADMINISTRATIVO;
SELECT * FROM APJ_VOL_SANITARIO;
SELECT * FROM APJ_ALIMENTO;
SELECT * FROM APJ_ENVIO_ALIMENTICIO_ALIMETOS;
SELECT * FROM APJ_ENVIO_ALIMENTO;
SELECT * FROM APJ_ENVIO_MEDICAMENTO;
SELECT * FROM APJ_ENVIO_MEDICAMENTO_MEDICINAS;



/*INSERTS*/
INSERT INTO APJ_SEDE(CVE_SEDE,NOMBRE_SEDE,CIUDAD_SEDE,UBICACION_SEDE,NOMBRE_DIRECTOR_SEDE)
VALUES (01,'Abristor ONG', 'Colorado','Terrance Way #62', 'Jesica Sans');
INSERT INTO APJ_SEDE(CVE_SEDE,NOMBRE_SEDE,CIUDAD_SEDE,UBICACION_SEDE,NOMBRE_DIRECTOR_SEDE)
VALUES (02,'Trito COOP', 'Reino Unido','Bell Route #30', 'Brian Figueras');
INSERT INTO APJ_SEDE(CVE_SEDE,NOMBRE_SEDE,CIUDAD_SEDE,UBICACION_SEDE,NOMBRE_DIRECTOR_SEDE)
VALUES (03,'Handless S.A', 'Republica D','Ivory Boulevard #86', 'Borja Vives');
INSERT INTO APJ_SEDE(CVE_SEDE,NOMBRE_SEDE,CIUDAD_SEDE,UBICACION_SEDE,NOMBRE_DIRECTOR_SEDE)
VALUES (04,'Servo ONG', 'Brasil','Senna Route #294', 'Demetrio Barroso');
INSERT INTO APJ_SEDE(CVE_SEDE,NOMBRE_SEDE,CIUDAD_SEDE,UBICACION_SEDE,NOMBRE_DIRECTOR_SEDE)
VALUES (05,'Parade COOP', 'Canada','Penrouse Avenue #486', 'Benito Arcos');
INSERT INTO APJ_SEDE(CVE_SEDE,NOMBRE_SEDE,CIUDAD_SEDE,UBICACION_SEDE,NOMBRE_DIRECTOR_SEDE)
VALUES (06,'Tizanal S.R.L', 'CDMX','Polanco #40', 'Pedro Pablo Blasco');

SELECT * FROM APJ_SEDE;

INSERT INTO APJ_SOCIO(ID_SOCIO,NOMBRE_SOCIO,DIRECCION_SOCIO,TELEFONO_SOCIO,CUENTA_SOCIO,TIPO_CUOTA,IMPORTE,FECHA_PAGO,CVE_SEDE1)
VALUES (01,'Isabel Macias','Ash Lane #89','7266038216', 'ASLN123', 'C',600, '29-08-2024', 01);
INSERT INTO APJ_SOCIO(ID_SOCIO,NOMBRE_SOCIO,DIRECCION_SOCIO,TELEFONO_SOCIO,CUENTA_SOCIO,TIPO_CUOTA,IMPORTE,FECHA_PAGO,CVE_SEDE1)
VALUES (02,'Pilar Ballester','Angel Row #462','8522136163', 'PIRBLR459', 'C',15000, '23-06-2024', 02);
INSERT INTO APJ_SOCIO(ID_SOCIO,NOMBRE_SOCIO,DIRECCION_SOCIO,TELEFONO_SOCIO,CUENTA_SOCIO,TIPO_CUOTA,IMPORTE,FECHA_PAGO,CVE_SEDE1)
VALUES (03,'Olga Maria Felipe','Gold Route #258','71775391', 'OGMAFP190', 'C',20000, '30-05-2024', 03);
INSERT INTO APJ_SOCIO(ID_SOCIO,NOMBRE_SOCIO,DIRECCION_SOCIO,TELEFONO_SOCIO,CUENTA_SOCIO,TIPO_CUOTA,IMPORTE,FECHA_PAGO,CVE_SEDE1)
VALUES (04,'Emilia Calero','Luna Way #156','891280507', 'EMLCO654', 'C',16000, '01-11-2024', 04);
INSERT INTO APJ_SOCIO(ID_SOCIO,NOMBRE_SOCIO,DIRECCION_SOCIO,TELEFONO_SOCIO,CUENTA_SOCIO,TIPO_CUOTA,IMPORTE,FECHA_PAGO,CVE_SEDE1)
VALUES (05,'Manuel Cornejo','Carolina Norte #143','1916465963', 'MULCTO580', 'C',20000, '24-11-2024', 04);
INSERT INTO APJ_SOCIO(ID_SOCIO,NOMBRE_SOCIO,DIRECCION_SOCIO,TELEFONO_SOCIO,CUENTA_SOCIO,TIPO_CUOTA,IMPORTE,FECHA_PAGO,CVE_SEDE1)
VALUES (06,'Gisela Farre','Honor Street #414','0862109554', 'GISLB093', 'C',150000, '03-12-2024', 06);

SELECT * FROM APJ_SOCIO;

INSERT INTO APJ_VOL_ADMINISTRATIVO(ID_ADMIN, NSS_ADMIN, EDAD_ADMIN, NOMBRE_ADMIN, TEL_ADMIN, DIRECCION_ADMIN, CVE_SEDE2)
VALUES(01, '72795608040', '21', 'Joseba Buendia', '7445021497','La condeza #343', 01);
INSERT INTO APJ_VOL_ADMINISTRATIVO(ID_ADMIN, NSS_ADMIN, EDAD_ADMIN, NOMBRE_ADMIN, TEL_ADMIN, DIRECCION_ADMIN, CVE_SEDE2)
VALUES(02, '15088701667', '20', 'Maria Martin', '6074645690','Petal Way #6', 02);
INSERT INTO APJ_VOL_ADMINISTRATIVO(ID_ADMIN, NSS_ADMIN, EDAD_ADMIN, NOMBRE_ADMIN, TEL_ADMIN, DIRECCION_ADMIN, CVE_SEDE2)
VALUES(03, '91806083439', '23', 'Piedad Romera', '2567508006','Mason #562', 03);
INSERT INTO APJ_VOL_ADMINISTRATIVO(ID_ADMIN, NSS_ADMIN, EDAD_ADMIN, NOMBRE_ADMIN, TEL_ADMIN, DIRECCION_ADMIN, CVE_SEDE2)
VALUES(04, '10806022653', '30', 'Jonatan Latorre', '6633870226','Paradaise #660', 04);
INSERT INTO APJ_VOL_ADMINISTRATIVO(ID_ADMIN, NSS_ADMIN, EDAD_ADMIN, NOMBRE_ADMIN, TEL_ADMIN, DIRECCION_ADMIN, CVE_SEDE2)
VALUES(05, '55550123467', '27', 'Anabel Melagar', '2408983074','Lane #462', 05);
INSERT INTO APJ_VOL_ADMINISTRATIVO(ID_ADMIN, NSS_ADMIN, EDAD_ADMIN, NOMBRE_ADMIN, TEL_ADMIN, DIRECCION_ADMIN, CVE_SEDE2)
VALUES(06, '23709003459', '19', 'Aitana Cobos', '4704441463','La Plaza #407', 06);

SELECT * FROM APJ_VOL_ADMINISTRATIVO;

INSERT INTO APJ_VOL_SANITARIO(ID_SANIT, NSS_SANIT, EDAD_SANIT, DIRECCION_SANIT, PROFESION_SANIT, DISPONIBILIDAD_SANIT, NUM_TRABAJOS_SANIT, TEL_SANIT, CVE_SEDE3)
VALUES(01, '40821711120', '34','Chapel #297','Medico General', 'SI', '30','4536574029',01);
INSERT INTO APJ_VOL_SANITARIO(ID_SANIT, NSS_SANIT, EDAD_SANIT, DIRECCION_SANIT, PROFESION_SANIT, DISPONIBILIDAD_SANIT, NUM_TRABAJOS_SANIT, TEL_SANIT, CVE_SEDE3)
VALUES(02, '66543171832', '25','Esmeralda #05','Enfermero', 'SI', '15','2337626282',02);
INSERT INTO APJ_VOL_SANITARIO(ID_SANIT, NSS_SANIT, EDAD_SANIT, DIRECCION_SANIT, PROFESION_SANIT, DISPONIBILIDAD_SANIT, NUM_TRABAJOS_SANIT, TEL_SANIT, CVE_SEDE3)
VALUES(03, '71231948398', '28','Aitana #725','Medico General', 'NO', '5','1523764486',03);
INSERT INTO APJ_VOL_SANITARIO(ID_SANIT, NSS_SANIT, EDAD_SANIT, DIRECCION_SANIT, PROFESION_SANIT, DISPONIBILIDAD_SANIT, NUM_TRABAJOS_SANIT, TEL_SANIT, CVE_SEDE3)
VALUES(04, '96566110145', '45','Amaya #677','Cirujano', 'SI', '45','3790751243',04);
INSERT INTO APJ_VOL_SANITARIO(ID_SANIT, NSS_SANIT, EDAD_SANIT, DIRECCION_SANIT, PROFESION_SANIT, DISPONIBILIDAD_SANIT, NUM_TRABAJOS_SANIT, TEL_SANIT, CVE_SEDE3)
VALUES(05, '78129045923', '34','Aviation #337','Enfermero', 'SI', '15','6605097133',05);

SELECT* FROM APJ_VOL_SANITARIO;

INSERT INTO APJ_ENVIO_ALIMENTO(CVE_ENVIOA, DESTINO_ENVIOA, FECHA_SALIDA_ENVIOA, SEDE_ENVIOA)
VALUES (01,'Alemania', '02-05-2025','Approfuse S.A');
INSERT INTO APJ_ENVIO_ALIMENTO(CVE_ENVIOA, DESTINO_ENVIOA, FECHA_SALIDA_ENVIOA, SEDE_ENVIOA)
VALUES (02,'Japon', '17-09-2025','Thorrupt O.N.G');
INSERT INTO APJ_ENVIO_ALIMENTO(CVE_ENVIOA, DESTINO_ENVIOA, FECHA_SALIDA_ENVIOA, SEDE_ENVIOA)
VALUES (03,'LAOS', '06-07-2024','Mentiffy S.A');
INSERT INTO APJ_ENVIO_ALIMENTO(CVE_ENVIOA, DESTINO_ENVIOA, FECHA_SALIDA_ENVIOA, SEDE_ENVIOA)
VALUES (04,'India', '25-05-2025','Disible S.A');
INSERT INTO APJ_ENVIO_ALIMENTO(CVE_ENVIOA, DESTINO_ENVIOA, FECHA_SALIDA_ENVIOA, SEDE_ENVIOA)
VALUES (05,'Peru', '30-03-2025','Producina S.A');

SELECT * FROM APJ_ENVIO_ALIMENTO;

INSERT INTO APJ_ALIMENTO(CVE_ALIMENTO,TIPO_ALIMENTO,DESCRIPCION_ALIMENTO)
VALUES(01, 'Granos','Avena');
INSERT INTO APJ_ALIMENTO(CVE_ALIMENTO,TIPO_ALIMENTO,DESCRIPCION_ALIMENTO)
VALUES(02, 'Granos','Arroz');
INSERT INTO APJ_ALIMENTO(CVE_ALIMENTO,TIPO_ALIMENTO,DESCRIPCION_ALIMENTO)
VALUES(03, 'Proteina','Pescado');
INSERT INTO APJ_ALIMENTO(CVE_ALIMENTO,TIPO_ALIMENTO,DESCRIPCION_ALIMENTO)
VALUES(04, 'Proteina','Atun');
INSERT INTO APJ_ALIMENTO(CVE_ALIMENTO,TIPO_ALIMENTO,DESCRIPCION_ALIMENTO)
VALUES(5, 'Granos','Soja');

SELECT * FROM APJ_ALIMENTO;

INSERT APJ_ENVIO_ALIMENTICIO_ALIMETOS(CVE_ENVIOA1, CVE_ALIMENTO1, NUMERO_TONELADAS)
VALUES(01,01,300);
INSERT APJ_ENVIO_ALIMENTICIO_ALIMETOS(CVE_ENVIOA1, CVE_ALIMENTO1, NUMERO_TONELADAS)
VALUES(02,02,500);
INSERT APJ_ENVIO_ALIMENTICIO_ALIMETOS(CVE_ENVIOA1, CVE_ALIMENTO1, NUMERO_TONELADAS)
VALUES(03,03,6000);
INSERT APJ_ENVIO_ALIMENTICIO_ALIMETOS(CVE_ENVIOA1, CVE_ALIMENTO1, NUMERO_TONELADAS)
VALUES(04,04,5000);

SELECT * FROM APJ_ENVIO_ALIMENTICIO_ALIMETOS;

INSERT APJ_MEDICAMENTO(CVE_MEDICAMENTO,TIPO_MEDICAMENTO,DESCRIPCION_MEDICAMENTO)
VALUES(01, 'Analgesico','Aspirina, Naproxeno');
INSERT APJ_MEDICAMENTO(CVE_MEDICAMENTO,TIPO_MEDICAMENTO,DESCRIPCION_MEDICAMENTO)
VALUES(02,  'Analgesico', 'Metamizol');
INSERT APJ_MEDICAMENTO(CVE_MEDICAMENTO, TIPO_MEDICAMENTO, DESCRIPCION_MEDICAMENTO)
VALUES(03, 'Antiinflamatorios','Carisoprodol');
INSERT APJ_MEDICAMENTO(CVE_MEDICAMENTO, TIPO_MEDICAMENTO, DESCRIPCION_MEDICAMENTO)
VALUES(04, 'Analgesico','Aspirina');

INSERT APJ_ENVIO_MEDICAMENTO(CVE_ENVIOM,DESTINO_ENVIOM,FECHA_SALIDA_ENVIOM,SEDE_ENVIOM)
VALUES (01, 'Ucrania', '29/05/2024','Sandy ORG');
INSERT APJ_ENVIO_MEDICAMENTO(CVE_ENVIOM,DESTINO_ENVIOM,FECHA_SALIDA_ENVIOM,SEDE_ENVIOM)
VALUES (02, 'Ucrania', '29/05/2024','Sandy ORG');
INSERT APJ_ENVIO_MEDICAMENTO(CVE_ENVIOM,DESTINO_ENVIOM,FECHA_SALIDA_ENVIOM,SEDE_ENVIOM)
VALUES (03, 'Palestina', '29/05/2024','Paraside OOP');

INSERT APJ_ENVIO_PERSONAL(CVE_ENVIOP, DESTINO_ENVIOP, FECHA_SALIDA_ENVIOP)
VALUES(01, 'Palestina', '28/07/2025');
INSERT APJ_ENVIO_PERSONAL(CVE_ENVIOP, DESTINO_ENVIOP, FECHA_SALIDA_ENVIOP)
VALUES(02, 'Corea del Norte', '04/07/2025');
INSERT APJ_ENVIO_PERSONAL(CVE_ENVIOP, DESTINO_ENVIOP, FECHA_SALIDA_ENVIOP)
VALUES(03, 'Argentina', '04/07/2025');

INSERT APJ_ENVIO_PERSONAL_SANITARIO(CVE_ENVIOP1,ID_SANIT1,NUMERO_TONELADAS)
VALUES(01,01,5000);
INSERT APJ_ENVIO_PERSONAL_SANITARIO(CVE_ENVIOP1,ID_SANIT1,NUMERO_TONELADAS)
VALUES(02,02,6000);
INSERT APJ_ENVIO_PERSONAL_SANITARIO(CVE_ENVIOP1,ID_SANIT1,NUMERO_TONELADAS)
VALUES(03,03,1000);

SELECT * FROM APJ_ENVIO_MEDICAMENTO_MEDICINAS;




SELECT NOMBRE_SOCIO, CUENTA_SOCIO, IMPORTE
FROM APJ_SOCIO
WHERE IMPORTE>20000;

SELECT TEL_ADMIN, EDAD_ADMIN EDAD_SANIT, TEL_SANIT
FROM APJ_VOL_ADMINISTRATIVO, APJ_VOL_SANITARIO
WHERE EDAD_ADMIN<27;

SELECT PROFESION_SANIT, NUM_TRABAJOS_SANIT, NOMBRE_SEDE, NOMBRE_DIRECTOR_SEDE 
FROM APJ_VOL_SANITARIO, APJ_SEDE 
WHERE CVE_SEDE3 = CVE_SEDE;

SELECT * FROM APJ_ENVIO_MEDICAMENTO;
SELECT * FROM APJ_ENVIO_MEDICAMENTO_MEDICINAS;
SELECT * FROM APJ_MEDICAMENTO;
SELECT * FROM APJ_ALIMENTO;
SELECT * FROM APJ_ENVIO_ALIMENTO;
SELECT * FROM APJ_SOCIO;
SELECT * FROM APJ_VOL_ADMINISTRATIVO;
SELECT * FROM APJ_VOL_SANITARIO;
SELECT * FROM APJ_SEDE;

SELECT MAX (EDAD_SANIT) VOLUNTARIO_MAYOR, MIN(EDAD_SANIT) VOLUNTARIO_MENOR,
(MAX (EDAD_SANIT) - MIN (EDAD_SANIT)) DIFERENCIA_EDAD
FROM APJ_VOL_SANITARIO;

SELECT MAX (IMPORTE) IMPORTE_ALTO, MIN(IMPORTE) IMPORTE_BAJO,
(MAX (IMPORTE) + MIN (IMPORTE)) TOTAL_DE_TRANSFERENCIAS
FROM APJ_SOCIO;

SELECT MAX (EDAD_ADMIN) ADMINISTRADOR_MAYOR, MIN( EDAD_ADMIN) ADMINISTRADOR_MENOR,
(MAX (EDAD_ADMIN) - MIN (EDAD_ADMIN)) DIFERENCIA_DE_EDAD
FROM APJ_VOL_ADMINISTRATIVO;

SELECT NOMBRE_SEDE, COUNT(*) AS CUENTA_SEDE
FROM APJ_SEDE
GROUP BY NOMBRE_SEDE;

SELECT AVG(NUM_TRABAJOS_SANIT) PROMEDIO FROM APJ_VOL_SANITARIO;

SELECT NSS_ADMIN, NSS_SANIT
FROM APJ_SEDE
INNER JOIN APJ_VOL_ADMINISTRATIVO ON CVE_SEDE2=CVE_SEDE
INNER JOIN APJ_VOL_SANITARIO ON CVE_SEDE3=CVE_SEDE;

SELECT DESCRIPCION_ALIMENTO, COUNT(CVE_ALIMENTO1) AS NUMERO_ENVIOS
FROM APJ_ENVIO_ALIMENTICIO_ALIMETOS INNER JOIN APJ_ALIMENTO
ON CVE_ALIMENTO= CVE_ALIMENTO1
GROUP BY DESCRIPCION_ALIMENTO
ORDER BY COUNT(CVE_ALIMENTO1) DESC;

SELECT * FROM APJ_SEDES_SOCIOS1;
SELECT * FROM APJ_ENVIOS_MEDICAMENTOS3;
SELECT * FROM APJ_ENVIOS_M;
SELECT * FROM APJ_COSITAS;
SELECT * FROM APJ_ENVIO_MEDICAMENTO;
SELECT * FROM APJ_ENVIO_MEDICAMENTO_MEDICINAS;
SELECT * FROM APJ_MEDICAMENTO;
SELECT * FROM APJ_SOCIO;
SELECT * FROM APJ_SEDE;
SELECT * FROM APJ_VOL_ADMINISTRATIVO;
SELECT * FROM APJ_VOL_SANITARIO;

/*ALGEBRA RELACIONAL*/

/*PROYECCION*/

SELECT NOMBRE_SOCIO, CUENTA_SOCIO, IMPORTE, FECHA_PAGO FROM APJ_SOCIO;

/*RESTRICCION*/

SELECT NOMBRE_SEDE, NOMBRE_DIRECTOR_SEDE, NOMBRE_SOCIO, CUENTA_SOCIO, IMPORTE
FROM APJ_SEDE, APJ_SOCIO
WHERE CVE_SEDE=CVE_SEDE1
AND IMPORTE>1000

/*PRODUCTO CARTESIANO*/

SELECT DESTINO_ENVIOA, DESTINO_ENVIOM, FECHA_SALIDA_ENVIOA, FECHA_SALIDA_ENVIOM
FROM APJ_ENVIO_ALIMENTO
CROSS JOIN APJ_ENVIO_MEDICAMENTO;

CREATE VIEW PERSONALVOL AS(
SELECT NOMBRE_ADMIN, PROFESION_SANIT
FROM APJ_VOL_ADMINISTRATIVO, APJ_VOL_SANITARIO);

SELECT * FROM PERSONALVOL;

/*JOIN*/

CREATE VIEW APJ_VOLUNTARIOS_SEDE AS(
SELECT NSS_ADMIN, NOMBRE_ADMIN, PROFESION_SANIT, NOMBRE_SEDE, NOMBRE_DIRECTOR_SEDE
FROM APJ_VOL_ADMINISTRATIVO INNER JOIN APJ_VOL_SANITARIO
ON CVE_SEDE2=CVE_SEDE3 INNER JOIN APJ_SEDE
ON CVE_SEDE=CVE_SEDE2);

SELECT * FROM APJ_VOLUNTARIOS_SEDE;
SELECT * FROM APJ_VOL_ADMINISTRATIVO;
SELECT * FROM APJ_VOL_SANITARIO;





CREATE VIEW APJ_ENVIOS_M AS
(SELECT NOMBRE_SEDE, DESTINO_ENVIOM, FECHA_SALIDA_ENVIOM AS'MEDICINAS'
FROM APJ_SEDE INNER JOIN APJ_ENVIO_MEDICAMENTO ON CVE_SEDE=SEDE_ENVIOM);

ALTER VIEW APJ_COSITAS AS
(SELECT NOMBRE_SEDE, NOMBRE_DIRECTOR_SEDE,FECHA_SALIDA_ENVIOM ,DESCRIPCION_MEDICAMENTO
FROM APJ_SEDE INNER JOIN APJ_ENVIO_MEDICAMENTO ON CVE_SEDE=SEDE_ENVIOM INNER JOIN APJ_ENVIO_MEDICAMENTO_MEDICINAS ON CVE_ENVIOM=CVE_ENVIOM1
INNER JOIN APJ_MEDICAMENTO ON CVE_MEDICAMENTO=CVE_MEDICAMENTO1);


ALTER VIEW APJ_SEDES_SOCIOS1 AS
(SELECT NOMBRE_SEDE, NOMBRE_DIRECTOR_SEDE, NOMBRE_SOCIO AS 'SEDES Y SOCIOS'
FROM APJ_SEDE INNER JOIN APJ_SOCIO ON CVE_SEDE=CVE_SEDE1);


alter VIEW APJ_ENVIOS_MEDICAMENTOS3 AS
(SELECT NUMERO_UNIDADES,TIPO_MEDICAMENTO, SEDE_ENVIOM AS 'Envios Medicos' from APJ_MEDICAMENTO
INNER JOIN APJ_ENVIO_MEDICAMENTO_MEDICINAS ON CVE_MEDICAMENTO1=CVE_MEDICAMENTO INNER JOIN APJ_ENVIO_MEDICAMENTO ON CVE_ENVIOM=CVE_ENVIOM1);


CREATE INDEX IDX_APJ_SOCIO_NOMBRE ON APJ_SOCIO (ID_SOCIO);
SELECT* FROM APJ_SOCIO WHERE ID_SOCIO=01;

CREATE INDEX IDX_APJ_SEDE ON APJ_SEDE(CVE_SEDE);
SELECT * FROM APJ_SEDE WHERE CVE_SEDE=05;

CREATE INDEX IDX_APJ_VOL_ADMIN ON APJ_VOL_ADMINISTRATIVO(ID_ADMIN);
SELECT * FROM APJ_VOL_ADMINISTRATIVO WHERE ID_ADMIN=2;

CREATE INDEX IDX_AOJ_VOL_SANITARIO ON APJ_VOL_SANITARIO(ID_SANIT);
SELECT * FROM APJ_VOL_SANITARIO WHERE ID_SANIT=3;

CREATE INDEX IDX_APJ_ENVIO_ALIMENTO ON APJ_ENVIO_ALIMENTO(CVE_ENVIOA);
SELECT * FROM APJ_ENVIO_ALIMENTO WHERE CVE_ENVIOA=01;

CREATE VIEW APJ_SEDES AS(
SELECT NOMBRE_SEDE, CIUDAD_SEDE
FROM APJ_SEDE);

SELECT * FROM APJ_SEDES;

CREATE VIEW APJ_SOCIOS AS(
SELECT NOMBRE_SOCIO, CUENTA_SOCIO
FROM APJ_SOCIO);

SELECT * FROM APJ_SOCIOS;

CREATE VIEW APJ_SEDE_Y_VOLUNTARIO AS(
SELECT NOMBRE_SEDE, NOMBRE_DIRECTOR_SEDE, NOMBRE_SOCIO
FROM APJ_SEDE, APJ_SOCIO);

SELECT * FROM APJ_SEDE_Y_VOLUNTARIO;

CREATE VIEW APJ_TODOS_VOLUNTARIOS AS (
SELECT EDAD_SANIT, TEL_ADMIN, EDAD_ADMIN,TEL_SANIT
FROM APJ_VOL_SANITARIO, APJ_VOL_ADMINISTRATIVO);

SELECT* FROM APJ_TODOS_VOLUNTARIOS;

CREATE VIEW APJ_TODOS_LOS_ENVIOS AS(
SELECT DESTINO_ENVIOA, SEDE_ENVIOA, FECHA_SALIDA_ENVIOA, DESTINO_ENVIOM, SEDE_ENVIOM, FECHA_SALIDA_ENVIOM
FROM APJ_ENVIO_ALIMENTO, APJ_ENVIO_MEDICAMENTO);


SELECT * FROM APJ_TODOS_LOS_ENVIOS;
SELECT * FROM APJ_ENVIO_MEDICAMENTO;
SELECT* FROM APJ_MEDICAMENTO;
SELECT * FROM APJ_ENVIO_MEDICAMENTO;

INSERT APJ_ENVIO_MEDICAMENTO_MEDICINAS(CVE_ENVIOM1, CVE_MEDICAMENTO1, NUMERO_UNIDADES)
VALUES(1,1,100);
INSERT APJ_ENVIO_MEDICAMENTO_MEDICINAS(CVE_ENVIOM1, CVE_MEDICAMENTO1, NUMERO_UNIDADES)
VALUES(2,2,100);



INSERT APJ_ENVIO_PERSONAL(CVE_ENVIOP, DESTINO_ENVIOP, FECHA_SALIDA_ENVIOP
VALUES(,,);

INSERT APJ_ENVIO_PERSONAL_SANITARIO(CVE_ENVIOP1,ID_SANIT1,NUMERO_TONELADAS)
VALUES(,,,);

SELECT * FROM APJ_SEDE;




create procedure CP_APJ_Insertar_Sede
@Cve int,
@SEDE varchar(15),
@Ciudad varchar(15),
@Ubicacion varchar(30),
@Nombre_director varchar(20)
as
insert into APJ_SEDE
values (@Cve,@SEDE, @Ciudad, @Ubicacion,@Nombre_director);
EXECUTE CP_APJ_Insertar_Sede 07, 'KARIO S.A','Veracruz', 'Mar #345', 'Carlos Flores';
EXECUTE CP_APJ_Insertar_Sede 10, 'STARLON S.A','Canada', 'Londres #25', 'Tobias Holmes';
EXECUTE CP_APJ_Insertar_Sede 11, 'STARLON S.A','Canada', 'Londres #25', 'Tobias Holmes';


SELECT * FROM APJ_SEDE;


create procedure CP_APJ_Vol_Admin
@Id int
as
select EDAD_SANIT, DIRECCION_SANIT, PROFESION_SANIT
from APJ_VOL_SANITARIO
WHERE ID_SANIT = @Id;
EXECUTE CP_APJ_Vol_Admin 04;
create procedure CP_APJ_Actualizar_Sede
@Cve int,
@Ciudad varchar(15)
as
update APJ_SEDE
set CIUDAD_SEDE= @Ciudad
where CVE_SEDE= @Cve;
execute CP_APJ_Actualizar_Sede 7, 'Iztapalapa';

SELECT * FROM APJ_SEDE;



create procedure CP_APJ_Insertar_Socio
@id_socio int,
@Nombre_S varchar (15),
@Direc_S varchar (30),
@Tel_S varchar (10),
@Cuenta_S varchar (18),
@Tipo_C varchar (1), 
@importe int,
@fecha_pago varchar (10),
@cve_s1 int
as
insert into APJ_SOCIO 
values (@id_socio,@Nombre_S,@Direc_S,@Tel_S,@Cuenta_S,@Tipo_C,@importe,@fecha_pago,@cve_s1);

create procedure CP_APJ_eliminar_vol_administrativo
@ID_adm int
as
DELETE APJ_VOL_ADMINISTRATIVO WHERE ID_ADMIN= @ID_adm;
execute CP_APJ_eliminar_vol_administrativo 04;

SELECT * FROM APJ_VOL_ADMINISTRATIVO;

create trigger CT_APJ_Insertar_SEDE
on APJ_SEDE
for Insert
as
select * from inserted

SELECT * FROM APJ_SEDE;
SELECT * FROM APJ_SOCIO;

EXECUTE CP_APJ_Insertar_Sede 12, 'Blow ONG', 'E.U.A', 'Washinton #05', 'Tobias Londra';

alter trigger CT_APJ_Actualizar_Socio
on APJ_SEDE
instead of update
as
declare @CVE_SEDE1 int
select @CVE_SEDE1= CVE_SEDE from inserted
update APJ_SOCIO
set CVE_SEDE1=@CVE_SEDE1
where CVE_SEDE1 = @CVE_SEDE1;

update APJ_SEDE set CVE_SEDE=12 where CVE_SEDE=1;

SELECT * FROM APJ_SEDE;
SELECT * FROM APJ_SOCIO;

create trigger CT_APJ_Eliminar_Sede
on APJ_SEDE
for Delete
as update APJ_SOCIO
set CVE_SEDE1=NULL
from deleted
where APJ_SOCIO.CVE_SEDE1=deleted.CVE_SEDE;

drop trigger CT_APJ_Eliminar_Sede;

create trigger CT_APJ_Eliminar_Medicamento
on APJ_MEDICAMENTO
instead of Delete
as update APJ_ENVIO_MEDICAMENTO_MEDICINAS
set CVE_MEDICAMENTO1=NULL
from deleted
where APJ_ENVIO_MEDICAMENTO_MEDICINAS.CVE_MEDICAMENTO1=deleted.CVE_MEDICAMENTO;
delete 
from APJ_MEDICAMENTO
from deleted
where APJ_MEDICAMENTO.CVE_MEDICAMENTO=deleted.CVE_MEDICAMENTO;


create procedure CP_APJ_Eliminar_Medicamento
@CVE_M int
as
delete
from APJ_MEDICAMENTO
where CVE_MEDICAMENTO=@CVE_M;
execute CP_APJ_Eliminar_Medicamento 01;

SELECT * FROM APJ_MEDICAMENTO;
SELECT * FROM APJ_ENVIO_MEDICAMENTO_MEDICINAS;
SELECT * FROM APJ_ENVIO_MEDICAMENTO;


CREATE LOGIN admin1 WITH PASSWORD = '66890';
USE APJBSDA;
SP_GRANTDBACCESS 'admin1';
GRANT SELECT, INSERT, UPDATE, DELETE
ON APJ_SOCIO
TO admin1

REVOKE DELETE TO admin1;









