CREATE TABLE APJ_ARTICULO (
CVE_ARTICULO INT PRIMARY KEY NOT NULL,
ARTICULO VARCHAR(20),
PRECIO FLOAT (2),
STOCK INT
);

CREATE TABLE APJ_VENTA(
CVE_VTA INT PRIMARY KEY NOT NULL,
FECHA_VTA VARCHAR(10),
HORA VARCHAR(10)
);

CREATE TABLE APJ_VENTA_PRODUCTO(
CVE_VTA1 INT FOREIGN KEY REFERENCES APJ_VENTA(CVE_VTA),
ARICULO1 INT FOREIGN KEY REFERENCES APJ_ARTICULO(CVE_ARTICULO),
CANTIDAD INT
);

begin try
	begin tran
	update AAPJ_ARTICULO