CREATE DATABASE TIENDAAPJ;

CREATE TABLE AAPJ_ARTICULO (
CV_ARTICULO INT IDENTITY(1,1) PRIMARY KEY (CV_ARTICULO),
ARTICULO VARCHAR(20),
PRECIO FLOAT (2),
STOCK INT
);

CREATE TABLE AAPJ_VENTA(
CV_VTA INT IDENTITY(1,1) PRIMARY KEY(CV_VTA),
FECHA_VTA VARCHAR(10),
HORA VARCHAR(10)
);

CREATE TABLE AAPJ_VENTA_PRODUCTO(
CVE_VTA1 INT FOREIGN KEY REFERENCES AAPJ_VENTA(CV_VTA),
ARICULO1 INT FOREIGN KEY REFERENCES AAPJ_ARTICULO(CV_ARTICULO),
CANTIDAD INT
);

INSERT INTO AAPJ_ARTICULO(ARTICULO,PRECIO,STOCK)
VALUES('Agua enbasada',8,15); 
INSERT INTO AAPJ_ARTICULO(ARTICULO,PRECIO,STOCK)
VALUES('Agua enbasada',10,5); 
INSERT INTO AAPJ_ARTICULO(ARTICULO,PRECIO,STOCK)
VALUES('Refresco',12,17); 

BEGIN TRY
	begin tran
	update AAPJ_ARTICULO
	set STOCK= STOCK-13
	where CV_ARTICULO=2
	insert into AAPJ_VENTA(FECHA_VTA,HORA)
	values (GETDATE(), GETDATE());
	insert into AAPJ_VENTA_PRODUCTO(CVE_VTA1,ARICULO1,CANTIDAD)
	values(1,2,13)
	select ARTICULO, STOCK, (PRECIO*CANTIDAD) as IMPORTE
	from AAPJ_ARTICULO, AAPJ_VENTA_PRODUCTO
	where CV_ARTICULO=CVE_VTA1
	commit tran
END TRY
begin catch
rollback tran
end catch

SELECT * FROM AAPJ_ARTICULO;
SELECT * FROM AAPJ_VENTA;
SELECT * FROM AAPJ_VENTA_PRODUCTO;