CREATE TABLE APJ_ACTOR_PRINCIPAL(
ID_ACT_PRINCIPAL VARCHAR(20),
NOM_ACT_PRINCIPAL VARCHAR(20),
TEL_ACT_PRINCIPAL VARCHAR(20),
DOMICILIO VARCHAR(20)
);
CREATE TABLE APJ_PAPEEL(
CVE_PAPEL VARCHAR(20),
DESCRIPCION VARCHAR(20),
PAGO FLOAT(5),
EDAD VARCHAR (20)
);
CREATE TABLE APJ_PELIICULA(
CVE_PEL VARCHAR(20),
DESCRIPCION VARCHAR(20),
TIPO_PEL VARCHAR(20),
DURACION VARCHAR(20)
);
CREATE TABLE APJ_EXTRAA(
DNI_EXTRA VARCHAR(20),
EXTRA VARCHAR(20),
TEL_EXTRA VARCHAR(20),
EXTRA_DIRECCION VARCHAR(20)
);
CREATE TABLE APJ_ACTOR_PELIICULA(
DNI_ACTOR VARCHAR (20),
CLAVE_PELICULA VARCHAR(20)
);
INSERT INTO APJ_ACTOR_PRINCIPAL(ID_ACT_PRINCIPAL, NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DOMICILIO)
VALUES ('A1','Juana Perez','56-57-20','Av 13');
INSERT INTO APJ_ACTOR_PRINCIPAL(ID_ACT_PRINCIPAL, NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DOMICILIO)
VALUES ('A2','Luis Gomez','14-34-12','Calle Zapotecas');
INSERT INTO APJ_ACTOR_PRINCIPAL(ID_ACT_PRINCIPAL, NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DOMICILIO)
VALUES ('A3','Maria Guzman','78-40-13','Periferico 123');
INSERT INTO APJ_ACTOR_PRINCIPAL(ID_ACT_PRINCIPAL, NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DOMICILIO)
VALUES ('A4','Pedro Juarez','77-34-90','Oriente 45');

SELECT * FROM APJ_ACTOR_PRINCIPAL;

INSERT INTO APJ_PAPEEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P1','Protagonista',10000,'20');
INSERT INTO APJ_PAPEEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P2','Secundario',8000,'21');
INSERT INTO APJ_PAPEEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P3','De reparto',5000,'19');
INSERT INTO APJ_PAPEEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P4','De pequenas partes',2500,'22');
INSERT INTO APJ_PAPEEL(CVE_PAPEL,DESCRIPCION,PAGO,EDAD)
VALUES ('P5','Figurante',2000,'23');

SELECT * FROM APJ_PAPEEL;

INSERT INTO APJ_PELIICULA(CVE_PEL, DESCRIPCION,TIPO_PEL,DURACION)
VALUES('PEL1','El fin del mundo','ACCION','3');
INSERT INTO APJ_PELIICULA(CVE_PEL, DESCRIPCION,TIPO_PEL,DURACION)
VALUES('PEL2','El regreso de Chuky','TERROR','2');
INSERT INTO APJ_PELIICULA(CVE_PEL, DESCRIPCION,TIPO_PEL,DURACION)
VALUES('PEL3','El pais maravillas','FANTASIA','2.5');
INSERT INTO APJ_PELIICULA(CVE_PEL, DESCRIPCION,TIPO_PEL,DURACION)
VALUES('PEL4','Mi suegra','COMEDIA','2');

SELECT * FROM APJ_PELIICULA;

INSERT INTO APJ_EXTRAA(DNI_EXTRA,EXTRA, TEL_EXTRA, EXTRA_DIRECCION)
VALUES ('A5','Ana Juarez','56-57-20','Av 20');
INSERT INTO APJ_EXTRAA(DNI_EXTRA,EXTRA, TEL_EXTRA, EXTRA_DIRECCION)
VALUES ('A2','Luis Gomez','14-34-12','Calle Zapotecas');
INSERT INTO APJ_EXTRAA(DNI_EXTRA,EXTRA, TEL_EXTRA, EXTRA_DIRECCION)
VALUES ('A6','Daniel Lopez','78-40-13','Sur 18');
INSERT INTO APJ_EXTRAA(DNI_EXTRA,EXTRA, TEL_EXTRA, EXTRA_DIRECCION)
VALUES ('A4','Pedro Juarez','77-34-90','Oriente 45');

SELECT * FROM APJ_EXTRAA;

INSERT INTO APJ_ACTOR_PELIICULA(DNI_ACTOR, CLAVE_PELICULA)
VALUES ('A1','PEL1');

SELECT NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL
FROM APJ_ACTOR_PELIICULA
UNION
SELECT EXTRA, TEL_EXTRA
FROM APJ_EXTRAA;

SELECT NOM_ACT_PRINCIPAL, TEL_ACT_PRINCIPAL, DESCRIPCION_PELICULA
FROM APJ_ACTOR_PRINCIPAL, APJ_PELIICULA, APJ_ACTOR_PELICULA
WHERE ID_ACT_PRINCIPAL = DNI_ACTOR1 AND CLAVE_PEL1=CLAVE_PEL
UNION 
SELECT NOM_EXTRA, TEL_EXTRA, DESCRIPCION_PELICULA
FROM APJ_EXTRA, APJ_PELICULA, DESCRIPCION_PELICULAFROM APJ_EXTRA, PELICULA ACTOR PELICULA
WHERE DNI_EXTRA=DNI_ACTOR1 AND CLAVE_PEL1=CVE-PEL:
SELECT DESCR

CREATE VIEW APJ_TODOS_ACTORES AS(
SELECT *
FROM APJ_ACTOR_PRINCIIAL
UNION 
SELECT *
FROM APJ_EXTRAA);

SELECT NOM_ACT_PRINCIPAL, TEL, DESCRFROM ACTORES PELICULA ACTOR PELICULA
WHERE IF ACT _ DNI ACTOR 1 AND CLAVE PEL1=CVE_PEL

select nom_extra,  extra_direccionfrom apj_extra
except select nom_principal, domicio-act
from APJ_ACTOR_PRINCIPAL

SELECT NOM_ACTOR_PRINCIPAL, DOMICIO, DESCRIPCION PELICULA
FROM APJ_TOFOD LOD ACCCOTRES INNER JOIN APJ_ACTOR_PLEICULA
ON ID_ACT_PRINCIPAL = DINQ_ACTOR1 INNER JOIN APJ_PELICULA
ON CLAVE_PEL1_CVE_PEL;

CREATE VIEW TODAS_LAS_TABLAS
