CREATE DATABASE APJ_REPASO_EXM;

CREATE TABLE APJ_PRODUCTOS(
ID_PRODUCTO INT PRIMARY KEY NOT NULL,
NOMBRE_PRODUCTO VARCHAR (20)
);

CREATE TABLE APJ_TIPO_PRODUCTO(
ID_PRODUCTO2 INT FOREIGN KEY REFERENCES APJ_PRODUCTOS(ID_PRODUCTO),
NOMBRE_PRODUCTO2 VARCHAR(30),
TIPO_PRODUCTO VARCHAR(20)
);