CREATE DATABASE EXAMEN_RSAPJ;
USE EXAMEN_RSAPJ;

CREATE TABLE APJ_PROFESOR_BASE(
RFC VARCHAR (20),
NOM_PROF VARCHAR (20),
ACADEMIA VARCHAR (20)
);

INSERT APJ_PROFESOR_BASE(RFC,NOM_PROF,ACADEMIA)
VALUES ('BAVR680902','RUTH BLAS','INFORMATICA');
INSERT APJ_PROFESOR_BASE(RFC,NOM_PROF,ACADEMIA)
VALUES ('SACL640623','LETICIA SALAS','INFORMATICA');
INSERT APJ_PROFESOR_BASE(RFC,NOM_PROF,ACADEMIA)
VALUES ('DUAX580816','XOCHIL DURAN','FISICA');

CREATE TABLE APJ_ALUMNO(
BOLETA VARCHAR (20),
NOM_ALUMNO VARCHAR (20),
EDAD VARCHAR (20)
);

SELECT * FROM APJ_ALUMNO;

INSERT APJ_ALUMNO(BOLETA,NOM_ALUMNO,EDAD)
VALUES ('200801','JUAN LOPEZ','20');
INSERT APJ_ALUMNO(BOLETA,NOM_ALUMNO,EDAD)
VALUES ('200902','ANA PEREZ','21');
INSERT APJ_ALUMNO(BOLETA,NOM_ALUMNO,EDAD)
VALUES ('200903','LUIS SANCHEZ','19');
INSERT APJ_ALUMNO(BOLETA,NOM_ALUMNO,EDAD)
VALUES ('200904','MARIA GUZMAN','22');
INSERT APJ_ALUMNO(BOLETA,NOM_ALUMNO,EDAD)
VALUES ('200005','ENRIQUE GONZALEZ','23');
INSERT APJ_ALUMNO(BOLETA,NOM_ALUMNO,EDAD)
VALUES ('200906','PEDRO JUAREZ','18');

CREATE TABLE APJ_MATERIA(
CVE_MATERIA VARCHAR (10),
DESCRIPCION VARCHAR(20),
CREDITOS VARCHAR (2)
);

INSERT APJ_MATERIA(CVE_MATERIA,DESCRIPCION,CREDITOS)
VALUES ('BD','BASE DE DATOS','8');
INSERT APJ_MATERIA(CVE_MATERIA,DESCRIPCION,CREDITOS)
VALUES ('SMBD','SISTEMAS MANEJADORES','8');
INSERT APJ_MATERIA(CVE_MATERIA,DESCRIPCION,CREDITOS)
VALUES ('F1','FISICA 1','6');

CREATE TABLE APJ_GRUPO(
ID_GRUPO VARCHAR (2),
SECUENCIA VARCHAR (5),
CVE_MATERIA VARCHAR (10),
CVE_PROFESOR VARCHAR (20),
SALON VARCHAR(10)
);

INSERT APJ_GRUPO(ID_GRUPO,SECUENCIA,CVE_MATERIA,CVE_PROFESOR,SALON)
VALUES ('1','4NM1','BD','BAVR680902','C1105');
INSERT APJ_GRUPO(ID_GRUPO,SECUENCIA,CVE_MATERIA,CVE_PROFESOR,SALON)
VALUES ('2','5NM3','SMBD','SACL640623','C1307');
INSERT APJ_GRUPO(ID_GRUPO,SECUENCIA,CVE_MATERIA,CVE_PROFESOR,SALON)
VALUES ('3','3IMI','F1','DUAX580816','CB208');
INSERT APJ_GRUPO(ID_GRUPO,SECUENCIA,CVE_MATERIA,CVE_PROFESOR,SALON)
VALUES ('4','5NM2','SMBD','BAVR680902','C1001');

CREATE TABLE APJ_ALUMNO_GRUPO(
BOLETA VARCHAR(6),
GRUPO VARCHAR(2)
);

INSERT APJ_ALUMNO_GRUPO(BOLETA,GRUPO)
VALUES ('200906','4');
INSERT APJ_ALUMNO_GRUPO(BOLETA,GRUPO)
VALUES ('200801','2');
INSERT APJ_ALUMNO_GRUPO(BOLETA,GRUPO)
VALUES ('200904','1');
INSERT APJ_ALUMNO_GRUPO(BOLETA,GRUPO)
VALUES ('200902','3');
INSERT APJ_ALUMNO_GRUPO(BOLETA,GRUPO)
VALUES ('200903','4');
INSERT APJ_ALUMNO_GRUPO(BOLETA,GRUPO)
VALUES ('200904','2');
INSERT APJ_ALUMNO_GRUPO(BOLETA,GRUPO)
VALUES ('200801','1');
INSERT APJ_ALUMNO_GRUPO(BOLETA,GRUPO)
VALUES ('200905','3');

CREATE TABLE APJ_PROFESOR_INTERNO(
RFC VARCHAR(11),
NOM_PROF VARCHAR (20),
ACADEMINA VARCHAR(30)
);

INSERT APJ_PROFESOR_INTERNO(RFC,NOM_PROF,ACADEMINA)
VALUES ('GOPA540709','ARMANDO GOMEZ','ADMINISTRACION');
INSERT APJ_PROFESOR_INTERNO(RFC,NOM_PROF,ACADEMINA)
VALUES ('GUMP640407','PEDRO GUDINO','MATEMATICAS');
INSERT APJ_PROFESOR_INTERNO(RFC,NOM_PROF,ACADEMINA)
VALUES ('DUAX580816','XOCHIL DURAN','FISICA');


CREATE TABLE APJ_CARRERA(
CVE_CARRERA VARCHAR(3),
DESCRPCION VARCHAR(20),
ESCUELA VARCHAR(10)
);

INSERT APJ_CARRERA(CVE_CARRERA,DESCRPCION,ESCUELA)
VALUES ('C1','CIENCIAS','UPIICSA');
INSERT APJ_CARRERA(CVE_CARRERA,DESCRPCION,ESCUELA)
VALUES ('A1','ADMINISTRACION','ESCA');
INSERT APJ_CARRERA(CVE_CARRERA,DESCRPCION,ESCUELA)
VALUES ('I1','INGENIERIA','ESIME');

SELECT * FROM APJ_GRUPO;
SELECT * FROM APJ_MATERIA;

SELECT DESCRIPCION, SECUENCIA
FROM APJ_MATERIA, APJ_GRUPO
WHERE APJ_MATERIA.CVE_MATERIA=APJ_GRUPO.CVE_MATERIA
AND CREDITOS<9

CREATE VIEW APJ_SALONES_ALUMNO_PROFESOR AS(
SELECT SALON, NOM_ALUMNO, NOM_PROF
FROM APJ_GRUPO
INNER JOIN APJ_ALUMNO_GRUPO ON ID_GRUPO= GRUPO
INNER JOIN APJ_ALUMNO ON APJ_ALUMNO_GRUPO.GRUPO= APJ_ALUMNO.BOLETA
INNER JOIN APJ_PROFESOR_BASE ON  APJ_GRUPO.CVE_PROFESOR= APJ_PROFESOR_BASE.RFC
);

SELECT * FROM APJ_SALONES_ALUMNO_PROFESOR;

SELECT RFC, NOM_PROF, ACADEMIA
FROM APJ_PROFESOR_BASE
INTERSECT
SELECT RFC, NOM_PROF, ACADEMINA
FROM APJ_PROFESOR_INTERNO

SELECT RFC, NOM_PROF
FROM APJ_PROFESOR_BASE
UNION
SELECT BOLETA, NOM_ALUMNO
FROM APJ_ALUMNO

CREATE VIEW APJ_MATERIA_CARRERA AS (
SELECT APJ_MATERIA.DESCRIPCION, APJ_CARRERA.DESCRPCION
FROM APJ_MATERIA, APJ_CARRERA
);

SELECT * FROM APJ_MATERIA_CARRERA;

SELECT NOM_PROF
FROM APJ_PROFESOR_INTERNO
EXCEPT 
SELECT NOM_PROF
FROM APJ_PROFESOR_BASE


CREATE VIEW CV_APJ_TP AS(
SELECT NOM_PROF, ACADEMIA
FROM APJ_PROFESOR_BASE
UNION
SELECT NOM_PROF, ACADEMINA
FROM APJ_PROFESOR_INTERNO
);

SELECT * FROM CV_APJ_TP;

CREATE TRIGGER CT_APJ_INSERTAR_PROFESOR
ON APJ_PROFESOR_BASE
FOR INSERT
AS
INSERT APJ_PROFESOR_INTERNO(APJ_PROFESOR_INTERNO.RFC,
APJ_PROFESOR_INTERNO.NOM_PROF, APJ_PROFESOR_INTERNO.ACADEMINA)
SELECT inserted.RFC, inserted.NOM_PROF, inserted.ACADEMIA);

CREATE TRIGGER CT_APJ_ACTUALIZAR_CLAVE
ON APJ_MATERIA
FROM UPDATE
AS
UPDATE APJ_GRUPO
SET APJ_GRUPO.CVE_MATERIA= interted.CVE_MATERIA
FROM inserted, deleted
WHERE APJ_GRUPO.CVE_MATERIA=deleted.CV_MATERIA

CREATE TRIGGER CT_APJ_ELIMINAR
ON APJ_GRUPO
FROM deleted
AS
UPDATE APJ_ALUMNO_GRUPO
SET GRUPO=NULL
FROM deleted





